# Trên Agent (Windows): C:\Program Files (x86)\ossec-agent
<syscheck> 
  <frequency>300</frequency> 
  <directories check_all="yes">C:\Users\Public</directories> 
  <directories check_all="yes">C:\Windows\System32</directories> 
  <directories check_all="yes">C:\Program Files</directories> 
</syscheck>


# /var/ossec/etc/ossec.conf trên Agent (Linux): 
<syscheck> 
  <frequency>300</frequency>  <!-- Quét mỗi 5 phút --> 
  <directories check_all="yes" realtime="yes">/var/www/html</directories> 
  <directories check_all="yes" realtime="yes">/tmp</directories> 
  <directories check_all="yes">/etc</directories> 
  <directories check_all="yes">/usr/bin</directories> 
</syscheck>


<localfile>
   <log_format>journald</log_format>
   <location>journald</location> 
</localfile>
